import os

os.system("fslmaths BA04_L.nii.gz -bin BA04_L.nii.gz")
os.system("fslmaths BA04_R.nii.gz -bin BA04_R.nii.gz")
os.system("fslmaths BA06_L.nii.gz -bin BA06_L.nii.gz")
os.system("fslmaths BA06_R.nii.gz -bin BA06_R.nii.gz")
os.system("fslmaths BA08_L.nii.gz -bin BA08_L.nii.gz")
os.system("fslmaths BA08_R.nii.gz -bin BA08_R.nii.gz")
os.system("fslmaths BA09_L.nii.gz -bin BA09_L.nii.gz")
os.system("fslmaths BA09_R.nii.gz -bin BA09_R.nii.gz")
os.system("fslmaths BA10_L.nii.gz -bin BA10_L.nii.gz")
os.system("fslmaths BA10_R.nii.gz -bin BA10_R.nii.gz")
os.system("fslmaths BA11_L.nii.gz -bin BA11_L.nii.gz")
os.system("fslmaths BA11_R.nii.gz -bin BA11_R.nii.gz")
os.system("fslmaths BA44_L.nii.gz -bin BA44_L.nii.gz")
os.system("fslmaths BA44_R.nii.gz -bin BA44_R.nii.gz")
os.system("fslmaths BA45_L.nii.gz -bin BA45_L.nii.gz")
os.system("fslmaths BA45_R.nii.gz -bin BA45_R.nii.gz")
os.system("fslmaths BA46_L.nii.gz -bin BA46_L.nii.gz")
os.system("fslmaths BA46_R.nii.gz -bin BA46_R.nii.gz")
os.system("fslmaths BA47_L.nii.gz -bin BA47_L.nii.gz")
os.system("fslmaths BA47_R.nii.gz -bin BA47_R.nii.gz")
os.system("fslmaths THAL_L.nii.gz -bin THAL_L.nii.gz")
os.system("fslmaths THAL_R.nii.gz -bin THAL_R.nii.gz")
os.system("fslmaths BNUCL_L.nii.gz -bin BNUCL_L.nii.gz")
os.system("fslmaths BNUCL_R.nii.gz -bin BNUCL_R.nii.gz")
os.system("fslmaths PLIC_L.nii.gz -bin PLIC_L.nii.gz")
os.system("fslmaths PLIC_R.nii.gz -bin PLIC_R.nii.gz")
os.system("fslmaths ALIC_L.nii.gz -bin ALIC_L.nii.gz")
os.system("fslmaths ALIC_R.nii.gz -bin ALIC_R.nii.gz")

